[server]
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
enableStaticServing = true

[ui]
hideTopBar = true

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

# Custom Fonts
[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-Regular.ttf"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-Medium.ttf"
style = "normal"
weight = 500

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-SemiBold.ttf"
style = "normal"
weight = 600

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/fonts/Poppins-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "Lato"
url = "app/static/fonts/Lato-Regular.ttf"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "Lato"
url = "app/static/fonts/Lato-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "Lato"
url = "app/static/fonts/Lato-Italic.ttf"
style = "italic"
weight = 400


# Theme Dark - Style Spotify
[theme]
base = "dark"
primaryColor = "#1ed760"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#1ed760"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
font = "Lato"
headingFont = "Poppins"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2.5rem", "2.25rem", "2rem", "1.5rem"]
codeFont = "SpaceMono"
codeFontSize = "0.75rem"
showSidebarBorder = true
chartCategoricalColors = ["#ffc862", "#2d46b9", "#b49bc8"]

[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#696969"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#1a1a1a"

